# Generated by Django 4.2.1 on 2023-08-20 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/bicycle/', verbose_name='登録する自転車の画像')),
                ('brand', models.CharField(choices=[('ALL-CITY', 'オールシティ'), ('ANCHOR', 'アンカー'), ('ARAYA', 'アラヤ'), ('ARGON18', 'アルゴンエイティーン'), ('AVEDIO', 'エヴァディオ'), ('BASSO', 'バッソ'), ('BE-ALL', 'ビーオール'), ('BH BIKES', 'ビーエイチ バイクス'), ('BIANCHI', 'ビアンキ'), ('BLUE', 'ブルー'), ('BMC', 'ビーエムシー'), ('BOMA', 'ボーマ'), ('BOOTLEG', 'ブートレック'), ('BOTTECCHIA', 'ボッテキア'), ('CALAMITA', 'カラミータ'), ('CANNONDALE', 'キャノンデール'), ('CARRERA', 'カレラ'), ('CASATI', 'カザーティ'), ('CENTURION', 'センチュリオン'), ('CERVELO', 'サーヴェロ'), ('CHERUBIN', 'ケルビム'), ('CHINELLI', 'チネリ'), ('CIELO', 'シエロ'), ('CIPOLLINI', 'チッポーニ'), ('COLNAGO', 'コルナゴ'), ('CORRATEC', 'コラテック'), ('DACCORD', 'ダコルディ'), ('DE ROSA', 'デ・ローザ'), ('DEDACCIAI STRADA', 'テダテャイ ストラーダ'), ('EDDYMERCKX', 'エディメルクス'), ('FELT', 'フェルト'), ('FOCUS', 'フォーカス'), ('FONDRIEST', 'フォンドリエスト'), ('FUJI', 'フジ'), ('GARNEAU', 'ガノー'), ('GIANT', 'ジャイアント'), ('GIOS', 'ジオス'), ('GT', 'ジーティー'), ('GUERCOTTI', 'グエルチョッティ'), ('INTERMAX', 'インターマックス'), ('JAMIS', 'ジェイミス'), ('KESTREL', 'ケストレル'), ('KHS', 'ケイ・ヘイチ・エス'), ('KOGA', 'コガ'), ('KONA', 'コナ'), ('KUOTA', 'クォータ'), ('LAPIERRE', 'ラピエール'), ('LEVEL', 'レベル'), ('LITESPEED', 'ライトスピード'), ('LOOK', 'ルック'), ('LOUISGARNEAU', 'ルイガノ'), ('MANHATTAN BIKE', 'マンハッタン バイク'), ('MASI', 'マジィ'), ('MBK', 'エムビーケー'), ('MERIDA', 'メリダ'), ('MIYATA JAPON', 'ミヤタ ジャポン'), ('MOOTS', 'ムーツ'), ('MUSEEUW', 'ムセウ'), ('NEILPRYDE', 'ニールプライド'), ('NEVI', 'ネービ'), ('OPERA', 'オペラ'), ('OPUS', 'オーパス'), ('ORBEA', 'オルベア'), ('PANASONIC', 'パナソニック'), ('PARLEE', 'パーリー'), ('PENNAROLA', 'ペンナローラ'), ('PINARELLO', 'ピナレロ'), ('PASSONI', 'パッソーニ'), ('RALEIGH', 'ラレー'), ('RHIDLEY', 'リドレー'), ('RITCHEY', 'リッチー'), ('RITEWYA', 'ライトウェイ'), ('SCHWINN', 'シュウィン'), ('SCOTT', 'スコット'), ('SPECIALIZED', 'スペシャライズド'), ('STORCK', 'ストーク'), ('SURLY', 'サーリー'), ('TIME', 'タイム'), ('TREK', 'トレック'), ('VELLUMCYCLES', 'ヴェラムサイクル'), ('WILIER', 'ウィリエール'), ('ZULLO', 'ズッロ')], max_length=50, verbose_name='ブランド')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='モデル')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='サイズ')),
                ('year', models.CharField(blank=True, max_length=100, null=True, verbose_name='年式')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partname', models.CharField(choices=[('FLAME', 'フレーム'), ('FRONTBRAKE', 'フロントブレーキ'), ('REARBRAKE', 'リアブレーキ'), ('CHAIN', 'チェーン'), ('FRONTTIRE', 'フロントタイヤ'), ('REARTIRE', 'リアタイヤ'), ('STEM', 'ステム'), ('SADDLE', 'サドル'), ('SEATPOST', 'シートポスト'), ('SEATCLAMP', 'シートクランプ'), ('PEDAL', 'ペダル'), ('FRONTLIGHT', 'フロントライト'), ('TAILLIGHT', 'テールライト')], max_length=100, verbose_name='パーツ名')),
                ('last_inspection_date', models.DateField(blank=True, max_length=100, null=True, verbose_name='点検日付（交換日）')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicycle_app.bicycle')),
            ],
        ),
    ]
