# Generated by Django 4.2.1 on 2023-07-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_bicycles_part_bicycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='bicycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.bicycle'),
        ),
    ]
