# Generated by Django 4.2.1 on 2023-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_part_partname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='image',
            field=models.ImageField(upload_to='images/bicycle/', verbose_name='登録する自転車の画像'),
        ),
        migrations.AlterField(
            model_name='part',
            name='partname',
            field=models.CharField(choices=[('FLAME', 'フレーム'), ('FRONTBRAKE', 'フロントブレーキ'), ('REARBRAKE', 'リアブレーキ'), ('CHAIN', 'チェーン'), ('FRONTTIRE', 'フロントタイヤ'), ('REARTIRE', 'リアタイヤ'), ('STEM', 'ステム'), ('SADDLE', 'サドル'), ('SEATPOST', 'シートポスト'), ('SEATCLAMP', 'シートクランプ'), ('PEDAL', 'ペダル'), ('FRONTLIGHT', 'フロントライト'), ('TAILLIGHT', 'テールライト'), ('BOTTLECAGE', 'ボトルケージ')], max_length=100, verbose_name='パーツ名'),
        ),
    ]
