# Generated by Django 4.2.1 on 2023-07-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bicycle_size_alter_bicycle_brand_alter_bicycle_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='bicycles',
            new_name='bicycle',
        ),
    ]
