# Generated by Django 4.2.1 on 2023-07-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_name_part_partname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='bicycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bicycle'),
        ),
    ]
