# Generated by Django 4.2.1 on 2023-08-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_part_bicycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='part',
            name='type',
        ),
        migrations.AlterField(
            model_name='part',
            name='partname',
            field=models.CharField(choices=[('FLAME', 'フレーム'), ('FRONTBRAKECALIPER', 'フロントブレーキ'), ('REARBRAKECALIPER', 'リアブレーキ'), ('CHAIN', 'チェーン'), ('FRONTTIRE', 'フロントタイヤ'), ('REARTIRE', 'リアタイヤ'), ('STEM', 'ステム'), ('SADDLE', 'サドル'), ('SEATPOST', 'シートポスト'), ('SEATCLAMP', 'シートクランプ'), ('PEDAL', 'ペダル'), ('FRONTPEDAL', 'フロントライト'), ('TAILPEDAL', 'テールライト'), ('BOTTLECAGE', 'ボトルケージ')], default=0, max_length=100, verbose_name='パーツ名'),
            preserve_default=False,
        ),
    ]
