# Generated by Django 4.2.1 on 2023-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_part_brand_remove_part_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='partname',
            field=models.CharField(choices=[('FLAME', 'フレーム'), ('FRONTBRAKE', 'フロントブレーキ'), ('REARBRAKE', 'リアブレーキ'), ('CHAIN', 'チェーン'), ('FRONTTIRE', 'フロントタイヤ'), ('REARTIRE', 'リアタイヤ'), ('STEM', 'ステム'), ('SADDLE', 'サドル'), ('SEATPOST', 'シートポスト'), ('SEATCLAMP', 'シートクランプ'), ('PEDAL', 'ペダル'), ('FRONTPEDAL', 'フロントライト'), ('TAILPEDAL', 'テールライト'), ('BOTTLECAGE', 'ボトルケージ')], max_length=100, verbose_name='パーツ名'),
        ),
    ]
