# Generated by Django 4.2.1 on 2023-08-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_bicycle_image_alter_part_partname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='partname',
            field=models.CharField(choices=[('FLAME', 'フレーム'), ('FRONTBRAKE', 'フロントブレーキ'), ('REARBRAKE', 'リアブレーキ'), ('CHAIN', 'チェーン'), ('FRONTTIRE', 'フロントタイヤ'), ('REARTIRE', 'リアタイヤ'), ('STEM', 'ステム'), ('SADDLE', 'サドル'), ('SEATPOST', 'シートポスト'), ('SEATCLAMP', 'シートクランプ'), ('PEDAL', 'ペダル'), ('FRONTLIGHT', 'フロントライト'), ('TAILLIGHT', 'テールライト')], max_length=100, verbose_name='パーツ名'),
        ),
    ]
