# Generated by Django 4.2.1 on 2023-06-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topimage', models.ImageField(upload_to='images', verbose_name=' トップ画像')),
            ],
        ),
    ]
