# Generated by Django 4.2.1 on 2023-06-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル'),
        ),
    ]
