# Generated by Django 4.2.1 on 2023-06-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_toppage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='サブタイトル'),
        ),
    ]
