# Generated by Django 4.2.1 on 2023-06-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_toppage_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='色')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='パーツ名')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='ブランド')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='タイプ')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='値段')),
                ('last_inspection_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後の点検日付（交換日）')),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='ブランド')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='モデル')),
                ('year', models.CharField(blank=True, max_length=100, null=True, verbose_name='年式')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.color')),
            ],
        ),
    ]
