# Generated by Django 4.2.1 on 2023-06-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bicycle_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppage',
            name='topimage',
            field=models.ImageField(upload_to='images/', verbose_name='トップ画像'),
        ),
    ]
