# Generated by Django 4.2.1 on 2023-06-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_toppage_topimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='color',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='bicyclphoto',
            field=models.ImageField(default=2023, upload_to='images/', verbose_name='登録する自転車の画像'),
            preserve_default=False,
        ),
    ]
