# Generated by Django 4.2.1 on 2023-06-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_bicycle_color_bicycle_bicyclphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='bicyclphoto',
            field=models.ImageField(upload_to='images/bycycle/', verbose_name='登録する自転車の画像'),
        ),
    ]
