# Generated by Django 4.2.1 on 2023-06-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_bicycle_bicyclphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
