# Generated by Django 4.2.1 on 2023-06-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bicycle_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='brand',
            field=models.CharField(choices=[('ALL-CITY', 'オールシティ'), ('ANCHOR', 'アンカー'), ('ARAYA', 'アラヤ'), ('ARGON18', 'アルゴンエイティーン'), ('AVEDIO', 'エヴァディオ'), ('BASSO', 'バッソ'), ('BE-ALL', 'ビーオール'), ('BH BIKES', 'ビーエイチ バイクス'), ('BIANCHI', 'ビアンキ'), ('BLUE', 'ブルー'), ('BMC', 'ビーエムシー'), ('BOMA', 'ボーマ'), ('BOOTLEG', 'ブートレック'), ('BOTTECCHIA', 'ボッテキア'), ('CALAMITA', 'カラミータ'), ('CANNONDALE', 'キャノンデール'), ('CARRERA', 'カレラ'), ('CASATI', 'カザーティ'), ('CENTURION', 'センチュリオン'), ('CERVELO', 'サーヴェロ'), ('CHERUBIN', 'ケルビム'), ('CHINELLI', 'チネリ'), ('CIELO', 'シエロ'), ('CIPOLLINI', 'チッポーニ'), ('COLNAGO', 'コルナゴ'), ('CORRATEC', 'コラテック'), ('DACCORD', 'ダコルディ'), ('DE ROSA', 'デ・ローザ'), ('DEDACCIAI STRADA', 'テダテャイ ストラーダ'), ('EDDYMERCKX', 'エディメルクス'), ('FELT', 'フェルト'), ('FOCUS', 'フォーカス'), ('FONDRIEST', 'フォンドリエスト'), ('FUJI', 'フジ'), ('GARNEAU', 'ガノー'), ('GIANT', 'ジャイアント'), ('GIOS', 'ジオス'), ('GT', 'ジーティー'), ('GUERCOTTI', 'グエルチョッティ'), ('INTERMAX', 'インターマックス'), ('JAMIS', 'ジェイミス'), ('KESTREL', 'ケストレル'), ('KHS', 'ケイ・ヘイチ・エス'), ('KOGA', 'コガ'), ('KONA', 'コナ'), ('KUOTA', 'クォータ'), ('LAPIERRE', 'ラピエール'), ('LEVEL', 'レベル'), ('LITESPEED', 'ライトスピード'), ('LOOK', 'ルック'), ('LOUISGARNEAU', 'ルイガノ'), ('MANHATTAN BIKE', 'マンハッタン バイク'), ('MASI', 'マジィ'), ('MBK', 'エムビーケー'), ('MERIDA', 'メリダ'), ('MIYATA JAPON', 'ミヤタ ジャポン'), ('MOOTS', 'ムーツ'), ('MUSEEUW', 'ムセウ'), ('NEILPRYDE', 'ニールプライド'), ('NEVI', 'ネービ'), ('OPERA', 'オペラ'), ('OPUS', 'オーパス'), ('ORBEA', 'オルベア'), ('PANASONIC', 'パナソニック'), ('PARLEE', 'パーリー'), ('PENNAROLA', 'ペンナローラ'), ('PINARELLO', 'ピナレロ'), ('PASSONI', 'パッソーニ'), ('RALEIGH', 'ラレー'), ('RHIDLEY', 'リドレー'), ('RITCHEY', 'リッチー'), ('RITEWYA', 'ライトウェイ'), ('SCHWINN', 'シュウィン'), ('SCOTT', 'スコット'), ('SPECIALIZED', 'スペシャライズド'), ('STORCK', 'ストーク'), ('SURLY', 'サーリー'), ('TIME', 'タイム'), ('TREK', 'トレック'), ('VELLUMCYCLES', 'ヴェラムサイクル'), ('WILIER', 'ウィリエール'), ('ZULLO', 'ズッロ')], default=1, max_length=100, verbose_name='ブランド'),
            preserve_default=False,
        ),
    ]
