# Generated by Django 4.2.1 on 2023-07-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_bicycle_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicycle',
            old_name='bicyclphoto',
            new_name='image',
        ),
    ]
