# Generated by Django 4.2.1 on 2023-07-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_bicyclphoto_bicycle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='price',
        ),
    ]
