# Generated by Django 4.2.1 on 2023-07-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_part_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
