# Generated by Django 4.2.1 on 2023-07-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
