# Generated by Django 4.2.1 on 2023-07-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='last_inspection_date',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='点検日付（交換日）'),
        ),
    ]
