# Generated by Django 4.2.1 on 2023-07-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_bicycle_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toppage',
        ),
    ]
