# Generated by Django 4.2.1 on 2023-07-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_toppage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='user',
        ),
    ]
